on: push
name: Publish Website
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 20
      - run: |
          git fetch --depth=20 origin +refs/tags/*:refs/tags/*
      - name: Deploy site
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          ftp-server: ftp://ftp.fireplacestudio.co.za/public_html/
          ftp-username: ${{ secrets.FTP_USER }}
          ftp-password: ${{ secrets.FTP_PWD }}

  test:
    name: Test, revert on failure or tag:deployed
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 20
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - uses: microsoft/playwright-github-action@v1
      - name: e2e tests
        run: npm install && npm run test
      - name: Fetch tag:deployed
        if: failure()
        uses: actions/checkout@master
        with:
          ref: deployed
          fetch-depth: 20
      - name: Fetch all branches for revert --depth=20
        if: failure()
        run: |
          git fetch --no-tags --prune --depth=20 origin +refs/heads/*:refs/remotes/origin/*
      - name: Revert deploy
        if: failure()
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          ftp-server: ftp://ftp.fireplacestudio.co.za/public_html/
          ftp-username: ${{ secrets.FTP_USER }}
          ftp-password: ${{ secrets.FTP_PWD }}
      - uses: actions/checkout@master
        with:
          fetch-depth: 20
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete tag at origin
        if: success()
        run: git push --delete origin deployed
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.17.2
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: deployed
